# Generated by Django 3.2.9 on 2021-11-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Вид кухни')),
                ('features', models.TextField(verbose_name='Особенности кухни')),
                ('url', models.CharField(default='/other/', max_length=32, verbose_name='Добавочный url')),
                ('flag', models.ImageField(blank=True, upload_to='flags')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название блюда')),
                ('discription', models.TextField(verbose_name='Описание блюда')),
                ('image', models.ImageField(blank=True, upload_to='dishes')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishesListApp.country', verbose_name='Вид кухни')),
            ],
        ),
    ]
