# Generated by Django 3.2.9 on 2021-11-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DishesListApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.PositiveIntegerField(default=1, verbose_name='Номер шага')),
                ('step_discription', models.TextField(verbose_name='Описание этапа приготовления')),
                ('image', models.ImageField(blank=True, upload_to='dishes', verbose_name='Фото этапа')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, upload_to='flags', verbose_name='Флаг страны'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes', verbose_name='Фото готового блюда'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishesListApp.dish', verbose_name='Название блюда'),
        ),
    ]
