# Generated by Django 3.2.9 on 2021-11-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DishesListApp', '0002_auto_20211105_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='features',
            new_name='discription',
        ),
        migrations.RemoveField(
            model_name='country',
            name='url',
        ),
    ]
